### PR TITLE
antd reusable components

### PR DESCRIPTION
**Pull request by ishanajmeri**
Adding remaining antd components.

### CODE REVIEW

**Comment by lokeshrana9999** [comment]
great work @ishanajmeri, just one suggestion-> For components like Collapse.Panel use the naming convention similar to Menu.Item as MenuItem for the file and component name and don't use the Collapse.Panel directly into the return statement instead do something like this 
const ADCollapsePanel = Collapse.Panel;

and then use ADCollapsePanel in jsx

**Comment by lokeshrana9999** [comment]
ps mention the issue in this pr and add the proptypes

**Comment by ishanajmeri** [comment]
I'm facing a problem with creating the following components If you gradually guide me with any one of them it'll be great.
1.modal
2. tree
3.treeselect
4.notification

**Comment by lokeshrana9999** [comment]
> I'm facing a problem with creating the following components If you gradually guide me with any one of them it'll be great.
> 1.modal
> 2. tree
> 3.treeselect
> 4.notification
@ishanajmeri is the way you implemented Anchor not working for these components?

**Comment by ishanajmeri** [comment]
No, it Can't happen that way. For example, In the modal component, there are two methods of calling it. 
The first is to call the modal by the property `visible`. In which there will be a **Button**. So by the **onClick** modal will be visible.
```js
<Button onClick={this.setState({visible='true'})> 
    Open Modal
 </Button>
<Modal visible={this.state.visible}>
 //children
</Modal>
```
The second method is to call the modal directly by the **Button**'s **onClick**  with constant.
```js
function info() {
  Modal.info({
    title: 'This is a notification message',
    content: (
      <div>
        <p>some messages...some messages...</p>
        <p>some messages...some messages...</p>
      </div>
    ),
  });
}
<Button onClick={info} >
Open Modal
</Button>
```
so how should I implement it?

**Comment by lokeshrana9999** [comment]
@ishanajmeri  For the  look module we only need to import it from antd similar to what you have done for anchor component.

the methods you mentioned are for implementation.

Normally this happens
[Import from antd] -> [Implementation].

What we are doing
[Import from antd] ->[export] -> [Import from look] -> [Implementation]

You just have to implement this([Import from antd] ->[export]) part

**Review by lokeshrana9999 — APPROVED** [review]

**Pull request merged**
